//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aflyatunov41
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickPoint
    {
        public int IDPoint { get; set; }
        public string indexPoint { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string number { get; set; }
    }
}
